### PR TITLE
fix: muk can mock accessor descriptor now

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by popomore** [comment]
```
Statements   : 97.78% ( 44/45 )
Branches     : 80% ( 8/10 )
Functions    : 100% ( 7/7 )
Lines        : 97.78% ( 44/45 )
```

**Comment by popomore** [comment]
ping @fent

**Comment by shaoshuai0102** [comment]
:+1:

**Comment by fent** [comment]
Looks good thanks!

I can merge and publish tonight.

**Comment by popomore** [comment]
@fent Great!

**Comment by fengmk2** [comment]
Great feature! +1984

**Pull request merged**
